### ISSUE TITLE
Uncaught SyntaxError: Unexpected token C

### ISSUE THREAD

**Issue by Vaquero84** [sadovnychyi/autocomplete-python#175] opened 2016-02-11 01:35 UTC
steps to reproduce below:

1. open python file
2. start typing

**Atom Version**: 1.5.1
**System**: MySystem
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v1.6.1

### Stack Trace

Uncaught SyntaxError: Unexpected token C

```
At file:///F:/Users/me/AppData/Local/atom/app-1.5.1/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22F%3A%5C%5CUsers%5C%5Cme%5C%5CDocuments%5C%5C_Psychologie%5C%5CStudium%5C%5C_Studentische%20Hilfskraft%5C%5CTheoretische%20Neurowissenschaft%5C%5CContent%5C%5CScripts%5C%5Cautosetup_master_mb2015.py%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22windowInitializationScript%22%3A%22F%3A%5C%5CUsers%5C%5Cme%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.5.1%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cinitialize-application-window.js%22%2C%22resourcePath%22%3A%22F%3A%5C%5CUsers%5C%5Cme%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.5.1%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.5.1%22%2C%22atomHome%22%3A%22F%3A%5C%5CUsers%5C%5Cme%5C%5C.atom%22%2C%22shellLoadTime%22%3A1157%2C%22initialPaths%22%3A%5B%22F%3A%5C%5CUsers%5C%5Cme%5C%5CDocuments%5C%5C_Psychologie%5C%5CStudium%5C%5C_Studentische%20Hilfskraft%5C%5CTheoretische%20Neurowissenschaft%5C%5CContent%5C%5CScripts%5C%5Cautosetup_master_mb2015.py%22%5D%2C%22windowState%22%3A%22%7B%7D%22%7D:1

SyntaxError: Unexpected token C
    at Object.parse (native)
    at [object Object].module.exports._deserialize (file:///F:/Users/me/.atom/packages/autocomplete-python/lib/provider.coffee:235:23)
    at provider.BufferedProcess.stdout (file:///F:/Users/me/.atom/packages/autocomplete-python/lib/provider.coffee:50:10)
    at Socket.<anonymous> (F:\Users\me\AppData\Local\atom\app-1.5.1\resources\app.asar\src\buffered-process.js:85:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

### Commands

```
     -4:04.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:54.4.0 core:delete (atom-text-editor.editor.is-focused)
  2x -2:52.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:47.1.0 core:save (atom-text-editor.editor.is-focused)
  3x -2:30.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:25.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:35 core:copy (atom-text-editor.editor.is-focused)
     -1:30.9.0 core:paste (atom-text-editor.editor.is-focused)
     -1:26.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:25.6.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -1:16.7.0 core:copy (atom-text-editor.editor.is-focused)
     -1:00.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:53.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:12.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:12.9.0 editor:indent (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "markdown-preview",
      "language-gfm",
      "language-gfm",
      "language-gfm"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.6.1
color-picker, v2.1.1
file-icons, v1.6.14
highlight-line, v0.11.1
language-autohotkey, v0.1.0
language-log, v1.3.0
language-markdown, v0.10.1
language-powershell, v2.1.0
linter, v1.11.3
linter-markdown, v1.4.2
linter-python-pep8, v0.2.0
markdown-preview-plus, v2.2.2
minimap, v4.19.0
pigments, vundefined
python-tools, v0.6.7

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment] 2016-02-11 06:00
Duplicate of #140.

**Closed by sadovnychyi** 2016-02-11 06:00 UTC
