### ISSUE TITLE
Error while updating: exit with code null, signal SIGTERM

### ISSUE THREAD

**Issue by RickDavis84** [sadovnychyi/autocomplete-python#24] opened 2015-06-25 21:54 UTC
on both windows & ubuntu immediately after clicking update for the autocomplete-python v 0.5.0 throws an error just saying "exit with code null, signal SIGTERM". The update appears to complete successfully though.

**Comment by sadovnychyi** [comment] 2015-06-26 05:07
As I have mentioned in #20 -- this is should be the last time you saw this error. Future update shouldn't spawn it.

Duplicate of #18 #20 #23 :open_mouth:

**Closed by sadovnychyi** 2015-06-26 05:07 UTC
